// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzftggoewfvaqotuytjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6ZnRnZ29ld2Z2YXFvdHV5dGp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MjI5MzQsImV4cCI6MjA2NTI5ODkzNH0.gTqqmTVrNq-S1FCGyn0wfq9NgTFzCyYcUrBO0XfCJHE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);